stages:
  - build
  - test
  - deploy

# Build stage
build:
  stage: build
  script:
    - echo "Building your project..."

# Test stage
test:
  stage: test
  script:
    - echo "Running tests..."

# Deploy stage
deploy:
  stage: deploy
  script:
    - echo "Deploying your project..."
