---
- name: Install Ansible
  ansible.builtin.apt:
    name: ansible
    state: present

- name: Install Kolla Ansible
  ansible.builtin.pip:
    name: kolla-ansible==12.8.0
    state: present

- name: Install Ansible
  ansible.builtin.apt:
    name: rsync
    state: present

- name: Create /etc/kolla directory
  ansible.builtin.file:
    path: /etc/kolla
    state: directory
    mode: "0755"

- name: Set ownership of /etc/kolla directory
  ansible.builtin.file:
    path: /etc/kolla
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    state: directory

- name: Copy Kolla configuration files to /etc/kolla
  ansible.builtin.shell:
    cmd: cp -R /usr/local/share/kolla-ansible/etc_examples/kolla/* /etc/kolla

- name: Copy Kolla inventory files to /etc/kolla
  ansible.builtin.shell:
    cmd: cp -R /usr/local/share/kolla-ansible/ansible/inventory/* /etc/kolla

- name: Generate Kolla passwords
  ansible.builtin.command:
    cmd: kolla-genpwd

- name: Copy SSH private key
  ansible.builtin.copy:
    content: "{{ lookup('env', 'PRIVATE_KEY') }}"
    dest: /home/ubuntu/.ssh/id_rsa
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '0600'

- name: Copy SSH private key
  ansible.builtin.copy:
    content: "{{ lookup('env', 'PRIVATE_KEY') }}"
    dest: /root/.ssh/id_rsa
    owner: root
    group: root
    mode: '0600'

- name: Tune /etc/ansible/ansible.cfg
  lineinfile:
    path: /etc/ansible/ansible.cfg
    line: "{{ item }}"
  with_items:
    - host_key_checking = False
    - pipelining = True
    - forks = 30
    - gathering = smart
    - fact_caching = jsonfile
    - fact_caching_connection = /root/ansible-facts
    - fact_caching_timeout = 0
    - timeout = 60
