---
- name: Copy globals.yml file to /etc/kolla/globals.yml
  copy:
    src: multinode
    dest: /etc/kolla/multinode

- name: Execute Kolla-ansible deploy command
  ansible.builtin.shell:
    cmd: kolla-ansible -i /etc/kolla/multinode bootstrap-servers

- name: Execute Kolla-ansible deploy command
  ansible.builtin.shell:
    cmd: kolla-ansible -i /etc/kolla/multinode prechecks

- name: Execute Kolla-ansible deploy command
  ansible.builtin.shell:
    cmd: kolla-ansible -i /etc/kolla/multinode deploy