---
- name: Fetch internal IP address
  ansible.builtin.set_fact:
    internal_ip: "{{ ansible_facts.default_ipv4.address }}"

- name: Fetch floating IP address
  ansible.builtin.set_fact:
    floating_ip: "{{ ansible_facts.all_ipv4_addresses | difference([ansible_facts.default_ipv4.address]) | first }}"

- name: Copy globals.yml file
  ansible.builtin.copy:
    src: globals.yml
    dest: /etc/kolla/globals.yml
    mode: '0644'

- name: Update Kolla configuration file with dynamic IP addresses
  ansible.builtin.lineinfile:
    path: /etc/kolla/globals.yml
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
  with_items:
    - { regexp: "^kolla_internal_vip_address:", line: "kolla_internal_vip_address: '{{ internal_ip }}'" }
    - { regexp: "^kolla_external_vip_address:", line: "kolla_external_vip_address: '{{ kolla_external_vip_address }}'" }

- name: Copy inventory file
  ansible.builtin.copy:
    src: multinode
    dest: /etc/kolla/
    mode: '0644'
