---
- name: Check if SSH key pair exists
  become: true
  become_user: ubuntu
  stat:
    path: /home/ubuntu/.ssh/id_rsa
  register: ssh_key_pair

- name: Generate SSH key pair
  become: true
  become_user: ubuntu
  command: ssh-keygen -t rsa -f ~/.ssh/id_rsa -q -N ""
  register: ssh_keypair_exists

- name: Copy SSH public key to other nodes
  become: true
  become_user: ubuntu
  authorized_key:
    user: ubuntu
    state: present
    key: "{{ lookup('file', '/home/ubuntu/.ssh/id_rsa.pub') }}"
  with_items:
    - "{{ groups['labst'] }}"
    - "{{ groups['labcm'] }}"
    - "{{ groups['labcr'] }}"

