---
- name: Check if SSH key pair exists
  stat:
    path: /root/.ssh/id_rsa
  register: ssh_key_pair

- name: Generate SSH key pair
  command: ssh-keygen -t rsa -f /root/.ssh/id_rsa -q -N ""

- name: Copy SSH public key to other nodes
  authorized_key:
    user: ubuntu
    state: present
    key: "{{ lookup('file', '/root/.ssh/id_rsa.pub') }}"
  with_items:
    - "{{ groups['labst'] }}"
    - "{{ groups['labcm'] }}"
    - "{{ groups['labcr'] }}"
