---
- name: Set environment variables
  set_fact:
    KOLLA_REPO_PORT: "17186"
    KOLLA_CONTAINER_OS: ubuntu
    KOLLA_CONTAINER_OPS: wallaby

- name: Create local Docker Registry directory
  ansible.builtin.file:
    path: /var/lib/registry
    state: directory

- name : Start and enable docker service
  systemd:
    state: started
    enabled: yes
    daemon_reload: yes
    name: docker

- name: Copy Docker image tar file
  copy:
    src: "{{ playbook_dir }}/registry.tar"
    dest: /tmp/registry.tar

- name: Untar Docker image
  unarchive:
    src: /tmp/registry.tar
    dest: /tmp/
    remote_src: yes

- name: Load Docker image
  shell: docker load -i /tmp/registry.tar

- name : Deploy a Local Docker Registry container
  ansible.builtin.docker_container:
    name: local_registry_server
    image: docker.io/registry:latest
    restart_policy: always
    ports:
      - "{{ KOLLA_REPO_PORT }}:5000"

- name: Pull kolla image from Docker Hub
  ansible.builtin.docker_image:
    source: pull
    force_source: yes
    name: "{{ docker_url }}/kolla/{{ KOLLA_CONTAINER_OS }}-binary-{{ item }}"
    tag: "{{ KOLLA_CONTAINER_OPS }}"
  loop: "{{ docker.images }}"

- name: Tag kolla image for Local Registry (replace localhost with your deployment node's IP)
  command:
    cmd: "docker tag {{ docker_url }}/kolla/{{ KOLLA_CONTAINER_OS }}-binary-{{ item }}:{{ KOLLA_CONTAINER_OPS }} localhost:{{ KOLLA_REPO_PORT }}/kolla/ubuntu-binary-{{ item }}:{{ KOLLA_CONTAINER_OPS }}"
  loop: "{{ docker.images }}"

- name: Push tagged image to Local Registry (replace localhost with your deployment node's IP)
  command:
    cmd: "docker push localhost:5000/kolla/ubuntu-binary-{{ item }}:{{ KOLLA_CONTAINER_OPS }}"
  loop: "{{ docker.images }}"
