---
# handlers file for os-configure
- name: Restart Network Service
  ansible.builtin.service:
    name: systemd-networkd
    state: restarted

- name: Restart SSH Service
  ansible.builtin.service:
    name: sshd
    state: restarted

- name: Restart systemd-timesyncd service
  ansible.builtin.service:
    name: systemd-timesyncd
    state: restarted
