---
ansible_uer: root
docker_url: artifactorycn.netcracker.com:17186
registry_image_tar: ./registry.tar
docker:
  images:
    - fluentd
    - kolla-toolbox
    - cron
#    - chrony
    - haproxy
    - keepalived
    - memcached
    - rabbitmq
    - mariadb-server
    - mariadb-clustercheck
    - keystone-fernet
    - keystone
    - keystone-ssh
    - glance-api
    - nova-api
    - nova-scheduler
    - nova-conductor
    - nova-ssh
    - nova-novncproxy
    - nova-libvirt
    - nova-compute
    - nova-ssh
    - placement-api
    - neutron-server
    - neutron-metadata-agent
    - neutron-l3-agent
    - neutron-dhcp-agent
    - neutron-openvswitch-agent
    - openvswitch-db-server
    - openvswitch-vswitchd #added
    - cinder-api
    - cinder-scheduler
    - cinder-volume
    - cinder-backup
    - horizon
    - mistral-api
    - mistral-engine
    - mistral-event-engine
    - mistral-executor
    - heat-api
    - heat-api-cfn
    - heat-engine
#    - collectd
    - prometheus-server
    - prometheus-cadvisor
    - prometheus-node-exporter
    - prometheus-openstack-exporter
    - prometheus-memcached-exporter
    - prometheus-haproxy-exporter
    - prometheus-mysqld-exporter
