---
# vars file for os-configure
#remote_repo_url: "http://reposrv.netcracker.com/sources.list.d/distr/netcracker_ubuntu_focal.list"
remote_repo:
  ubuntu:
    - deb http://yumsrv03cn.netcracker.com/deb/ubuntu/ focal main restricted
    - deb http://yumsrv03cn.netcracker.com/deb/ubuntu/ focal-updates main restricted
    - deb http://yumsrv03cn.netcracker.com/deb/ubuntu/ focal universe
    - deb http://yumsrv03cn.netcracker.com/deb/ubuntu/ focal-updates universe
    - deb http://yumsrv03cn.netcracker.com/deb/ubuntu/ focal multiverse
    - deb http://yumsrv03cn.netcracker.com/deb/ubuntu/ focal-updates multiverse
    - deb http://yumsrv03cn.netcracker.com/deb/ubuntu/ focal-backports main restricted universe multiverse

dir_path: "/srv/www"