---
- name: Create webuser
  user:
    name: webuser
    state: present

- name: Install Nginx package
  apt:
    name: nginx
    state: present

- name: Configure Nginx
  files:
    src: nginx.conf
    dest: /etc/nginx/sites-available/default

- name: Copy index.html template to new root
  template:
    src: index.html.j2
    dest: /srv/www/index.html
  notify:
    - restart nginx
