---
- name: Create webuser
  user:
    name: webuser

- name: Install nginx package
  apt:
    name: nginx
    state: present

#- name: Configure nginx
#  copy:
#    src: nginx.conf
#    dest: /etc/nginx/nginx.conf
#  notify: Restart Nginx service

- name: Copy default index.html
  template:
    src: index.html.j2
    dest: /srv/www/index.html
    owner: webuser
    group: webuser
    mode: 0644
  register: index_html_result

- name: Configure nginx
  copy:
    src: nginx.conf
    dest: /etc/nginx/nginx.conf
  notify: restart ngnix
  when: index_html_result.changed

#- name: Ensure Nginx service is running and enabled
#  service:
#    name: nginx
#    state: started
#    enabled: yes
