---
#- name: Check if OS is Ubuntu
- hosts: all
  remote_user: ubuntu
  become: yes
  tasks:
    - name: Check OS distribution
      debug:
        var: ansible_distribution
      failed_when: ansible_distribution != 'Ubuntu'
#    - name: Include os-configure role
#      include_role:
#        name: ssh_setup
    - name: Include os-configure role
      include_role:
        name: os_configure
    - name: Include nginx role
      include_role:
        name: nginx
